#!/bin/bash

set -o pipefail

source /opt/nvm/nvm.sh
nvm use 22

echo $OPENAI_API_KEY | codex login --with-api-key

export MAX_BUDGET_USD=11
export INPUT_TOKEN_PRICE=1.75e-6
export CACHED_INPUT_TOKEN_PRICE=0.175e-6
export OUTPUT_TOKEN_PRICE=14.0e-6
export TIMEOUT_SEC=4200

cat /task_description/description.md | python -u /agent/better_codex_wrapper.py \
  --skip-git-repo-check \
  --dangerously-bypass-approvals-and-sandbox \
  --model gpt-5.2-2025-12-11 \
  -c model_reasoning_effort="medium" | tee /tmp/output_log.json

STATUS=$?

tail -n 1 /tmp/output_log.json > /output/inference_metadata.json

if [ -f /output/inference_metadata.json ]; then chmod 666 /output/inference_metadata.json; fi

exit $STATUS