#!/bin/bash

echo $PATH

# Capture start time
start_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "The following is the prompt being sent to Claude:"
printf "Perform the task described below. You are required to implement the required changes.\n\n"
cat /task_description/description.md

(printf "Perform the task described below. You are required to implement the required changes.\n\n";
cat /task_description/description.md) | claude -p \
  --dangerously-skip-permissions \
  --verbose \
  --output-format stream-json \
  --model claude-sonnet-4-5-20250929 \
  --max-budget-usd 7.5 2>&1 | tee /tmp/output_log.json


# Report final metadata
tail -n 1 /tmp/output_log.json | jq --arg start_time "$start_time" '{
  cost_usd: .total_cost_usd,
  finish_reason: .subtype,
  start_time: $start_time,
  finish_time: (now | strftime("%Y-%m-%dT%H:%M:%SZ")),
  additional: null
}' > /output/inference_metadata.json
