#!/bin/bash
# Shell setup script for Bitcoin Core testing
# This script configures the shell environment and builds Bitcoin Core

set -e

cd /testbed

# Patch source files if needed (for compatibility with newer GCC/Boost 1.74)
if [ -f "src/httpserver.cpp" ] && ! grep -q "#include <deque>" src/httpserver.cpp; then
    echo "Patching httpserver.cpp for GCC compatibility..."
    sed -i '/#include <future>/a #include <deque>' src/httpserver.cpp
fi

# Fix CompareModifiedEntry operator() to be const
if [ -f "src/miner.h" ] && ! grep -q "bool operator()(const CTxMemPoolModifiedEntry &a, const CTxMemPoolModifiedEntry &b) const" src/miner.h; then
    echo "Patching miner.h for Boost 1.74 compatibility..."
    sed -i 's/bool operator()(const CTxMemPoolModifiedEntry &a, const CTxMemPoolModifiedEntry &b)/bool operator()(const CTxMemPoolModifiedEntry \&a, const CTxMemPoolModifiedEntry \&b) const/' src/miner.h
fi

# Fix txmempool.h comparators to be const
if [ -f "src/txmempool.h" ] && grep -q "bool operator()(const CTxMemPoolEntry& a, const CTxMemPoolEntry& b)$" src/txmempool.h; then
    echo "Patching txmempool.h comparators for Boost 1.74 compatibility..."
    sed -i 's/bool operator()(const CTxMemPoolEntry& a, const CTxMemPoolEntry& b)$/bool operator()(const CTxMemPoolEntry\& a, const CTxMemPoolEntry\& b) const/' src/txmempool.h
    sed -i 's/bool UseDescendantScore(const CTxMemPoolEntry &a)$/bool UseDescendantScore(const CTxMemPoolEntry \&a) const/' src/txmempool.h
fi

# Fix lockedpool.cpp missing include
if [ -f "src/support/lockedpool.cpp" ] && ! grep -q "#include <stdexcept>" src/support/lockedpool.cpp; then
    echo "Patching lockedpool.cpp for missing stdexcept include..."
    sed -i '1a #include <stdexcept>' src/support/lockedpool.cpp
fi

# Fix boost placeholders issue - add after all includes
for file in src/validation.cpp src/init.cpp src/torcontrol.cpp src/validationinterface.cpp; do
    if [ -f "$file" ] && grep -q "boost::bind" "$file" && ! grep -q "using boost::placeholders::" "$file"; then
        echo "Patching $file for Boost placeholders..."
        last_include=$(grep -n "^#include" "$file" | tail -1 | cut -d: -f1)
        sed -i "${last_include}a\\
\\
using boost::placeholders::_1;\\
using boost::placeholders::_2;\\
using boost::placeholders::_3;" "$file"
    fi
done

# Check if already configured
if [ ! -f "Makefile" ]; then
    echo "Running autogen.sh..."
    ./autogen.sh

    echo "Running configure..."
    ./configure --with-incompatible-bdb --enable-zmq --disable-bench \
                CXXFLAGS="-O0 -g"
fi

# Check if already built
if [ ! -f "src/bitcoind" ]; then
    echo "Building Bitcoin Core..."
    make -j2
fi

# Generate the test configuration file
if [ -d "test/functional" ]; then
    TEST_DIR="functional"
elif [ -d "test/rpc-tests" ]; then
    TEST_DIR="rpc-tests"
else
    echo "Error: Cannot find test directory"
    exit 1
fi

if [ ! -f "test/pull-tester/tests_config.ini" ]; then
    echo "Generating test configuration..."
    cat > test/pull-tester/tests_config.ini << EOF
# Automatically generated by setup_shell.sh
[components]
ENABLE_WALLET=True
ENABLE_UTILS=True
ENABLE_BITCOIND=True
ENABLE_ZMQ=True

[environment]
SRCDIR=/testbed
BUILDDIR=/testbed
EXEEXT=
EOF
fi

echo "Bitcoin Core build environment ready"
