#!/bin/bash

echo $PATH

# Capture start time
start_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "The following is the prompt being sent to Claude:"
cat /task_description/description.md

cat /task_description/description.md | claude -p \
  --dangerously-skip-permissions \
  --verbose \
  --output-format stream-json \
  --model claude-haiku-4-5-20251001 \
  --max-budget-usd 5 2>&1 | tee /tmp/output_log.json


# Report final metadata
tail -n 2 /tmp/output_log.json | jq -s --arg start_time "$start_time" '
  map(select(.type == "result")) | first | 
  {
    cost_usd: .total_cost_usd,
    start_time: $start_time,
    finish_time: (now | strftime("%Y-%m-%dT%H:%M:%SZ")),
    additional: null
  } 
  + (if .is_error then {finish_reason: "error"} else {finish_reason: .subtype} end)
' > /output/inference_metadata.json

chmod 666 /output/inference_metadata.json