#!/bin/bash

set -o pipefail


[ -s "/opt/nvm/nvm.sh" ] && source "/opt/nvm/nvm.sh"
nvm use 22

export MAX_BUDGET_USD=5.0
export INPUT_TOKEN_PRICE=0.07e-6
export OUTPUT_TOKEN_PRICE=0.27e-6

# Bifrost / OpenRouter Setup
# export OPENAI_API_KEY="$OPENROUTER_API_KEY"
# export OPENAI_BASE_URL="https://srlx.inf.ethz.ch/openai"
# export OPENAI_MODEL="qwen/qwen3-coder-30b-a3b-instruct:nitro"

mkdir -p .qwen
cat <<EOF > .qwen/settings.json
{
  "security": {
    "folderTrust": {
      "enabled": true
    }
  },
  "context": {
    "includeDirectories": ["/"]
  },
  "tools": {
    "enableToolOutputTruncation": true,
    "truncateToolOutputThreshold": 25000,
    "truncateToolOutputLines": 100,
    "approvalMode": "yolo",
    "autoAccept": true
  }
}
EOF

# Local Setup
export OPENAI_API_KEY="local-vllm" 
export OPENAI_BASE_URL="http://localhost:8023/v1"
export OPENAI_MODEL="Qwen/Qwen3-Coder-30B-A3B-Instruct-FP8"

echo "The following instruction is being sent to the agent:"
cat /task_description/description.md
echo ""


cat /task_description/description.md | python -u /agent/qwen_code_wrapper.py \
  --output-format stream-json \
  -y | tee /tmp/output_log.json

STATUS=$?

tail -n 1 /tmp/output_log.json > /output/inference_metadata.json

if [ -f /output/inference_metadata.json ]; then chmod 666 /output/inference_metadata.json; fi
  
exit $STATUS