#!/bin/bash

set -o pipefail

source /opt/nvm/nvm.sh
nvm use 22

echo $OPENAI_API_KEY | codex login --with-api-key

export MAX_BUDGET_USD=7.5
export INPUT_TOKEN_PRICE=1.25e-6
export CACHED_INPUT_TOKEN_PRICE=0.125e-6
export OUTPUT_TOKEN_PRICE=10.0e-6

cat /task_description/description.md | python -u /agent/codex_wrapper.py \
  --skip-git-repo-check \
  --dangerously-bypass-approvals-and-sandbox \
  --model gpt-5.1-codex-max \
  -c model_reasoning_effort="medium" | tee /tmp/output_log.json

# Capture the exit status of the pipeline
STATUS=$?

tail -n 1 /tmp/output_log.json > /output/inference_metadata.json

chmod 666 /output/inference_metadata.json