#!/bin/bash

set -o pipefail

source /opt/nvm/nvm.sh
nvm use 22

echo $OPENAI_API_KEY | codex login --with-api-key

export MAX_BUDGET_USD=2.5
export INPUT_TOKEN_PRICE=0.05e-6
export CACHED_INPUT_TOKEN_PRICE=0.005e-6
export OUTPUT_TOKEN_PRICE=0.4e-6
export TIMEOUT_SEC=4200

MODEL="gpt-5-nano-2025-08-07"
REASONING_EFFORT="medium"
TASK_DESCRIPTION="/task_description/description.md"

python -u /agent/better_codex_wrapper.py \
  --skip-git-repo-check \
  --dangerously-bypass-approvals-and-sandbox \
  --model "$MODEL" \
  -c model_reasoning_effort="$REASONING_EFFORT" < "$TASK_DESCRIPTION" \
  | tee /tmp/output_log.json
STATUS=${PIPESTATUS[0]}

tail -n 1 /tmp/output_log.json > /output/inference_metadata.json

if [ -f /output/inference_metadata.json ]; then chmod 666 /output/inference_metadata.json; fi # can move to entrypoint.sh
if [ -f /output/refactoring_plan.md ]; then chmod 666 /output/refactoring_plan.md; fi

exit $STATUS